name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: [self-hosted, Windows, X64] # Lenovo ThinkPad T410
            os-name: windows
            c_compiler: cl
            cpp_compiler: cl
            arch: x64
          - os: [self-hosted, Linux, X64, X11] # Liam-Desktop
            os-name: linux
            c_compiler: gcc
            cpp_compiler: g++
            arch: x64
            display: x11
          - os: [self-hosted, Linux, X64, Wayland] # Liam-Desktop
            os-name: linux
            c_compiler: gcc
            cpp_compiler: g++
            arch: x64
            display: wayland
          - os: [self-hosted, macOS, X64] # 2015-MacBook-Air
            os-name: mac
            c_compiler: clang
            cpp_compiler: clang++
            arch: x64

    steps:
    - name: Clean & clone
      shell: bash
      working-directory: ${{ github.workspace }}/..
      run: |
        rm -rf ./Roche-Limit
        git clone https://github.com/Liam-Weitzel/Roche-Limit Roche-Limit
        cd Roche-Limit
        git checkout "${{ github.sha }}"
        git submodule sync --recursive
        git submodule update --init --recursive --depth=1

    - name: Setup
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: eu-central-1
      run: |
        aws s3 cp "s3://${{ secrets.AWS_S3_BUCKET }}/rrespacker.zip" rrespacker.zip
        aws s3 cp "s3://${{ secrets.AWS_S3_BUCKET }}/steam_sdk.zip" steam_sdk.zip
        if [ "${{ matrix.os-name }}" = "windows" ]; then
          unzip -oq rrespacker.zip 'rrespacker.exe' -d "${{ github.workspace }}/client/libs/rrespacker/"
          unzip -oq steam_sdk.zip -d "${{ github.workspace }}/libs/steam/"
        fi
        if [[ "${{ matrix.os-name }}" = "linux" || "${{ matrix.os-name }}" = "mac" ]]; then
          unzip -q rrespacker.zip -d ${{ github.workspace }}/client/libs/rrespacker/
          chmod +x ${{ github.workspace }}/client/libs/rrespacker/*
          unzip -q steam_sdk.zip -d ${{ github.workspace }}/libs/steam/
        fi

    - name: Build client
      working-directory: ${{ github.workspace }}/client
      shell: bash
      run: |
        mkdir build/
        cd build/
        cmake \
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_SYSTEM_PROCESSOR=${{ matrix.arch }} \
        ${{ matrix.osx_deployment_target && format('-DCMAKE_OSX_DEPLOYMENT_TARGET={0}', matrix.osx_deployment_target) || '' }} \
        ${{ matrix.display == 'wayland' && '-DUSE_WAYLAND=ON -DUSE_X11=OFF' || '' }} \
        -S ..
        cmake --build . -j$(nproc) --verbose

    - name: Test client (Unix)
      if: matrix.os-name == 'linux' || matrix.os-name == 'mac'
      shell: bash
      working-directory: ${{ github.workspace }}/client
      run: |
        ./prep_models
        ./client_test

    - name: Test client (Windows)
      if: matrix.os-name == 'windows'
      shell: cmd
      working-directory: ${{ github.workspace }}/client
      run: |
        prep_models.exe
        client_test.exe

    - name: Zip client
      shell: bash
      run: |
        files=()
        while IFS= read -r file; do
          files+=("$file")
        done < <(
          for f in client/client.exe client/client client/client_test.exe client/client_test client/resources.rres client/lib_client.so client/lib_client.dll client/lib_client.dylib client/libsteam_api.so client/libsteam_api.dll client/libsteam_api.dylib client/steam_appid.txt; do
            [[ -f $f ]] && echo "$f"
          done | sort -u
        )

        if [[ "${{ matrix.os-name }}" == "windows" ]]; then
          temp_files=()
          while IFS= read -r file; do
            temp_files+=("$file")
          done < <(printf '%s\n' "${files[@]}" | xargs -I{} cygpath -w "{}" | sort -u)
          files=("${temp_files[@]}")
        fi

        zip $([[ "${{ matrix.os-name }}" == "windows" ]] && echo "a") client-${{ matrix.os-name }}-${{ matrix.arch }}${{ matrix.os-name == 'linux' && format('-{0}', matrix.display) || '' }}-${{ github.sha }}.zip "${files[@]}"

    - name: Upload client
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: eu-central-1
      run: |
        aws s3 cp ./client-${{ matrix.os-name }}-${{ matrix.arch }}${{ matrix.os-name == 'linux' && format('-{0}', matrix.display) || '' }}-${{ github.sha }}.zip s3://${{ secrets.AWS_S3_BUCKET }}

    - name: Build server
      shell: bash
      run: |
        cd "${{ github.workspace }}/server"
        mkdir build/
        cd build/
        cmake \
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_SYSTEM_PROCESSOR=${{ matrix.arch }} \
        ${{ matrix.osx_deployment_target && format('-DCMAKE_OSX_DEPLOYMENT_TARGET={0}', matrix.osx_deployment_target) || '' }} \
        -S ..
        cmake --build . -j$(nproc) --verbose

    - name: Test server (Unix)
      if: matrix.os-name == 'linux' || matrix.os-name == 'mac'
      shell: bash
      working-directory: ${{ github.workspace }}/server
      run: |
        echo "dummy"

    - name: Test server (Windows)
      if: matrix.os-name == 'windows'
      shell: cmd
      working-directory: ${{ github.workspace }}/server
      run: |
        echo dummy

    - name: Zip server
      shell: bash
      run: |
        files=()
        while IFS= read -r file; do
          files+=("$file")
        done < <(
          for f in server/CMakeLists.txt; do
            [[ -f $f ]] && echo "$f"
          done | sort -u
        )

        if [[ "${{ matrix.os-name }}" == "windows" ]]; then
          temp_files=()
          while IFS= read -r file; do
            temp_files+=("$file")
          done < <(printf '%s\n' "${files[@]}" | xargs -I{} cygpath -w "{}" | sort -u)
          files=("${temp_files[@]}")
        fi

        zip $([[ "${{ matrix.os-name }}" == "windows" ]] && echo "a") server-${{ matrix.os-name }}-${{ matrix.arch }}${{ matrix.os-name == 'linux' && format('-{0}', matrix.display) || '' }}-${{ github.sha }}.zip "${files[@]}"

    - name: Upload server
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: eu-central-1
      run: |
        aws s3 cp ./server-${{ matrix.os-name }}-${{ matrix.arch }}${{ matrix.os-name == 'linux' && format('-{0}', matrix.display) || '' }}-${{ github.sha }}.zip s3://${{ secrets.AWS_S3_BUCKET }}

  notify-discord:
    needs: build-test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify Discord
        shell: bash
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"${{ needs.build-test.result }}.\"}" \
               "${{ secrets.DISCORD_WEBHOOK_URL }}"
